[package]
name = "plonkhonk"
version = "0.1.0"
authors = ["Daniel Pagan <dpagan@gatech.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
glob = "0.3.0"
rayon = "1.3.0"
